services:
  python:
    container_name: python-server
    restart: unless-stopped
    image: britodfbr/estudo_llm:1.0.0
    build:
      context: ./container2
      dockerfile: Dockerfile

    volumes:
      - .:/code
networks:
  default:
    name: estudo_llm_network
