services:
   db:
    image: mariadb:10.2
    restart: unless-stopped
    env_file:
      - .env
    container_name: "ojs_db_${COMPOSE_PROJECT_NAME:-demo}"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-admin}"
      MYSQL_DATABASE: "${DB_DATABASE:-demo}"
      MYSQL_USER: "${DB_USER:-admin}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-admin}"
    volumes:
      - ./volumes/db:/var/lib/mysql
      - ./volumes/logs/db:/var/log/mysql
      - ./volumes/config/db.charset.conf:/etc/mysql/conf.d/charset.cnf
      - ./volumes/migration:/docker-entrypoint-initdb.d
