[default]
MSG="Hello World"
BG_COLOR='white'
FONT_COLOR='black'
TEMPLATE='system'
BLUE='#0060B5'
TZ='America/Sao_Paulo'
DEBUG_MODE=false
FORMAT_LOG="%(asctime)s;%(levelname)-8s;%(name)s;%(module)s;%(funcName)s;%(message)s"
FORMAT_LOG_WIN="$(asctime)s;$(levelname)-8s;$(name)s;$(module)s;$(funcName)s;$(message)s"
TIMEOUT=0.8

[development]
MSG="Hello Dev"
NAME="Application"
DEBUG_MODE=true

[testing]
MSG="Hello tester"
DEBUG_MODE=false

[production]
MSG="Hello User"
DEBUG_MODE=false
