[default]
MSG="Hello World"
BG_COLOR='white'
FONT_COLOR='black'
TEMPLATE='system'
BLUE='#0060B5'
TZ='America/Sao_Paulo'
FORMAT_LOG='%(asctime)s;%(levelname)-8s;%(name)s;%(module)s;%(funcName)s;%(message)s'

[development]
MSG="Hello Dev"
NAME="Application"

[testing]
MSG="Hello tester"

[production]
MSG="Hello User"
