services:
   db:
    image: mcr.microsoft.com/mssql/server:2019-CU16-GDR1-ubuntu-20.04
    restart: unless-stopped
    user: 0:0
    env_file:
      - .env
    container_name: "db_${COMPOSE_PROJECT_NAME:-demo}"
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 123!@#Asd
      MSSQL_PID: Express
      # MSSQL_PID: Developer
      MSQL_COLLATION: Latin1_General_CI_AI
      MSQL_AGENT_ENABLED: 1
      MSQL_MEMORY_LIMIT_MB: 1024
    volumes:
      - ./volumes/mssql-data:/var/opt/mssql/data
      - ./volumes/mssql-log:/var/opt/mssql/log
