version: '3.9'

networks:
  incolumedev:
    external: false

volumes:
  pg-database:

secrets:
  password:
    file: secrets.txt

services:

  jupyter:
    image: jupyter/scipy-notebook:python-3.10.6
    ports:
      - '8888:8888'
    restart: unless-stopped
    volumes:
      - ../:/home/jovyan/work
    depends_on:
      - db
    networks:
      incolumedev:

  db:
    image: postgres:14-alpine3.16
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=records
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pg-database:/var/lib/postgresql/data/
    networks:
      incolumedev:
