[project]
name = "ajedi20250522-estudo-langchain-huggingface"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Britodfbr", email = "britodfbr@gmail.com" }
]
requires-python = ">=3.10, <4"
dependencies = [
    "python-dotenv>=1.1.0",
]

[project.scripts]
ajedi-langchain-huggingface = "ajedi20250522_estudo_langchain_huggingface:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "faiss-cpu>=1.11.0",
    "huggingface-hub>=0.31.4",
    "langchain>=0.3.25",
    "langchain-huggingface>=0.2.0",
    "sentence-transformers>=4.1.0",
    "transformers>=4.52.3",
]
