version: '3.9'
services:
  apache:
    build:
      context: apache
    image: incolume/apache-local:0.1.0
    container_name: apache
    restart: unless-stopped
    ports:
      - 4900:80

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: incolume/nginx-local:0.1.0
    container_name: nginx
    restart: unless-stopped
    ports:
      - 4800:80
