version: "3.6"

networks:
  inside:
    external: false


services:
  webserver:
    image: nginx
    container_name: "nginx"
    hostname: "nginx"
    ports:
      - 80
      - 443
    volumes:
      - ./volume/html:/usr/share/nginx/html
    restart: always

