# File: docker-compose.yml
# Access via "http://localhost:8081"
#
# Call example:
# $ docker-compose up

version: '3.9'
networks:
  inside:
    external: false
services:
  db:
    image: postgres:${PGSQL_VERSION:-10-alpine3.16}
    restart: unless-stopped
    # env_file:
    #   - .env
    container_name: "${PROJECT_NAME:-default}_ojs_db"
    ports:
      - 5432:5432
    environment:
      POSTGRES_INITDB_ARGS: "--data-checksums"
      POSTGRES_USER: "${DB_USER:-admin}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-admin}"
      POSTGRES_DB: "${DB_DATABASE:-default}"
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
        #      - ./scripts/dbojssajhom_2022-04-27_bkp_pedidoSAJ.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - inside
  ojs:
    env_file:
      - .env
    environment:
      - OS_APP_BASE=${OS_APP_BASE:-alpine:3.12}
    image: incolume/ojs:3_2_1-4_${OS_APP_NAME:-alpine3.12}
    build:
      context: ojs
      args:
      - OS_APP_BASE=${OS_APP_BASE:-alpine:3.12}
    restart: unless-stopped
    container_name: "${PROJECT_NAME:-default}_ojs_app"
    hostname: "${PROJECT_NAME:-default}"
    ports:
      - "${HTTP_PORT:-8081}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./volumes/private:/var/www/files
      - ./volumes/public:/var/www/html/public
      - ./volumes/logs/app:/var/log/apache2
#      # WARNING: You can only enable file-volumes if file exists in the container.
#      - ./volumes/config/ojs.config.inc.php:/var/www/html/config.inc.php
#      - ./volumes/config/apache.htaccess:/var/www/html/.htaccess
#      - ./volumes/php.custom.ini:/usr/local/etc/php/conf.d/custom.ini

    networks:
      - inside
    depends_on:
      - db
