services:
  server:
    image: incolume/ajedi20250605_streamlit_docker:latest
    build:
      args:
        - DEBUG=1
      context: .
      dockerfile: Dockerfile
    container_name: server-ajedi20250605-streamlit
    working_dir: /code
    volumes:
      - .:/code
    # user: "1000"
    environment:
      - PYTHONUNBUFFERED=1
      - UV_LINK_MODE=copy
    ports:
      - 8500-8599:8500-8599

    command: >
      /bin/sh -c
      "uv venv
      && uv sync
      && source .venv/bin/activate
      && streamlit run --server.port 8501 --server.address 0.0.0.0 main.py"

    depends_on: []
    restart: unless-stopped
