server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    proxy_set_header Host $host; # Define o cabeçalho Host na solicitação
    proxy_set_header X-Real-IP $remote_addr; # Define o endereço IP real do cliente
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Define o endereço IP do proxy
    proxy_set_header X-Forwarded-Proto $scheme; # Define o protocolo da solicitação

    # location ~ ^/api(.*)$ {
        # proxy_pass http://backend-core:8000$1; # Redireciona o tráfego para o servidor back-end na porta designada
    # }

    location / {
        proxy_pass http://webapp:8501; # Redireciona o tráfego para o servidor back-end na porta designada
    }


}
