services:
  jupyter-server:
    # image: ${IMAGE_NAME:-incolume/container}:latest
    build:
      args:
        - DEBUG=${DEBUG:-True}
      context: .
      # dockerfile: Dockerfile
      dockerfile_inline: |
        # Dockerfile content goes here
        # This is an inline Dockerfile for the compose service
        FROM ghcr.io/astral-sh/uv:alpine3.21

        LABEL maintainer="Incolume.com.br"

        # Create a group and user
        # RUN addgroup -S appgroup && adduser -S appuser -G appgroup

        # Tell docker that all future commands should run as the appuser user
        # USER appuser

        # Define the working directory
        WORKDIR ${WORKDIR:-/code}

        # Install necessary packages
        RUN apk update && apk upgrade && apk add --no-cache build-base linux-headers git curl

        # Expose the necessary ports
        EXPOSE 22 80 443 8080 8888
        EXPOSE 8500-8599

        CMD echo 'Running server...' && tail -f /dev/null

    # container_name: jupyter-server
    working_dir: ${WORKDIR:-/code}
    volumes:
      - .:${WORKDIR:-/code}
    # user: "1000"
    environment:
      - PYTHONUNBUFFERED=1
      - UV_LINK_MODE=copy
      - OPEN_WEATHER_MAP_API_KEY=/run/secrets/APIKey
    ports:
      - 8888:8888
      - 8500-8599:8500-8599

    command: >
      /bin/sh -c
      "uv venv
      && uv sync
      && source .venv/bin/activate
      && uvx jupyter lab --allow-root --ip=0.0.0.0 --port=8888 --no-browser
      # && jupyter lab --allow-root --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token='xpto123' --NotebookApp.password='123' --NotebookApp.disable_check_xsrf=True
      "

    depends_on: []
    restart: unless-stopped

secrets:
   APIKey:
     file: secrets/token.txt
