[project]
name = "ajedi20250601-python-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Britodfbr", email = "britodfbr@gmail.com" }
]
requires-python = ">=3.10, <4"
dependencies = []

[project.scripts]
ajedi20250601-python-api = "ajedi20250601_python_api:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
