services:
  jupyter:
    container_name: estudo-rag
    environment:
      - BASEIMAGE=ubuntu:24.04  # Ubuntu 22.04.3 LTS
    image: incolume/ajedi20250523-estudo-rag:latest
    ports:
      - 8888:8888
    restart: unless-stopped
    volumes:
      - ../:/home/jovyan/work
