services:
  server:
    image: incolume/ajedi20250524-api-ibge:latest
    build:
      args:
      context: .
      dockerfile: Dockerfile
    container_name: server-api-ibge
    working_dir: /code
    volumes:
      - .:/code
    # user: "1000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 8501:8501

    command: uv run ajedi20250524-compose-dockerfile
    depends_on: []
