[project]
name = "ajedi20250607-dockerfile-inline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Britodfbr", email = "britodfbr@gmail.com" }
]
requires-python = ">=3.10, <4"
dependencies = [
    "httpx>=0.28.1",
    "icecream>=2.1.4",
    "streamlit>=1.45.1",
]

[project.scripts]
ajedi20250607-dockerfile-inline = "ajedi20250607_dockerfile_inline:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
