[project]
name = "ajedi20230223-openai-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <4"
dependencies = []

[dependency-groups]
dev = [
    "nltk>=3.9.1",
    "openai>=1.79.0",
    "scikit-learn>=1.6.1",
    "spellchecker>=0.4",
    "textblob>=0.19.0",
    "transformers>=4.52.3",
]
