version: '3.9'

services:
  py311:
    build:
      context: src
      dockerfile: Dockerfile
    image: env_python311
    command: 'python -m http.server 80'
    working_dir: /code
    volumes:
      - .:/code
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:7.0.5-alpine3.16
    ports:
      - '6379:6379'
    restart: unless-stopped


