[project]
name = "ajedi20250606-acesso-openweather"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <4"
dependencies = [
    "httpx>=0.28.1",
    "streamlit>=1.45.1",
]

[tool.uv.sources]
ajedi20250606_acesso_openweather = { workspace = true }

[dependency-groups]
dev = [
    "ajedi20250606_acesso_openweather",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"