[project]
name = "ajedi20250524-compose-dockerfile"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Britodfbr", email = "britodfbr@gmail.com" }
]
requires-python = ">=3.10, <4"
dependencies = []

[project.scripts]
ajedi20250524-compose-dockerfile = "ajedi20250524_compose_dockerfile:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "cowsay>=6.1",
    "icecream>=2.1.4",
]
