services:
  server:
    image: incolume/compose-dockerfile:20250524.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-compose-dockerfile
    working_dir: /code
    volumes:
      - .:/code
    # user: "1000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - BASEIMAGE=${BASEIMAGE:-ubuntu:latest}
    ports:
      - 8000:8000

    command: uv run ajedi20250524-compose-dockerfile
    depends_on: []


