[project]
name = "ajedi20250520-wrapper-docker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Britodfbr", email = "britodfbr@gmail.com" }
]
requires-python = ">=3.10, <4"
dependencies = []

[project.scripts]
ajedi20250520-wrapper-docker = "ajedi20250520_wrapper_docker:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "langchain-anthropic>=0.3.13",
    "langchain-community>=0.3.24",
    "langchain-google-genai>=2.1.4",
    "langchain-openai>=0.3.17",
]
